### PR TITLE
Update wrangler.toml configuration to latest wrangler version

### PR DESCRIPTION
**Pull request by lauragift21**
Updated the wrangler.toml config file to match the latest version of Wrangler.

### CODE REVIEW

**Review by JacobMGEvans — APPROVED** [review]
Should be merged after the wrangler1 deprecation efforts.

**Comment by charlypoly** [comment]
Hi @lauragift21,

Thank you for your contribution!
This change will also be introduce along with update to Yoga v3: https://github.com/the-guild-org/yoga-cloudflare-workers-template/pull/3

**Comment by JacobMGEvans** [comment]
If you have any questions regarding Wrangler2 migration feel free to reach out to either of us 😃

**Comment by charlypoly** [comment]
> If you have any questions regarding Wrangler2 migration feel free to reach out to either of us 😃

@JacobMGEvans, I'm definitely not a CF Worker expert, you're review of the current state of this template is more than welcome! 🤠

**Pull request closed without merging**
